/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-07 19:00:49 UTC)
 * on 2013-08-09 at 00:29:38 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.medals;

/**
 * Service definition for Medals (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link MedalsRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Medals extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://testapi-16.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "medals/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Medals(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Medals(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "insertMedalsType".
   *
   * This request holds the parameters needed by the the medals server.  After setting any optional
   * parameters, call the {@link InsertMedalsType#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.google.api.services.medals.model.MedalsType}
   * @return the request
   */
  public InsertMedalsType insertMedalsType(com.google.api.services.medals.model.MedalsType content) throws java.io.IOException {
    InsertMedalsType result = new InsertMedalsType(content);
    initialize(result);
    return result;
  }

  public class InsertMedalsType extends MedalsRequest<com.google.api.services.medals.model.MedalsType> {

    private static final String REST_PATH = "addMedaltype";

    /**
     * Create a request for the method "insertMedalsType".
     *
     * This request holds the parameters needed by the the medals server.  After setting any optional
     * parameters, call the {@link InsertMedalsType#execute()} method to invoke the remote operation.
     * <p> {@link InsertMedalsType#initialize(com.google.api.client.googleapis.services.AbstractGoogle
     * ClientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param content the {@link com.google.api.services.medals.model.MedalsType}
     * @since 1.13
     */
    protected InsertMedalsType(com.google.api.services.medals.model.MedalsType content) {
      super(Medals.this, "POST", REST_PATH, content, com.google.api.services.medals.model.MedalsType.class);
    }

    @Override
    public InsertMedalsType setAlt(java.lang.String alt) {
      return (InsertMedalsType) super.setAlt(alt);
    }

    @Override
    public InsertMedalsType setFields(java.lang.String fields) {
      return (InsertMedalsType) super.setFields(fields);
    }

    @Override
    public InsertMedalsType setKey(java.lang.String key) {
      return (InsertMedalsType) super.setKey(key);
    }

    @Override
    public InsertMedalsType setOauthToken(java.lang.String oauthToken) {
      return (InsertMedalsType) super.setOauthToken(oauthToken);
    }

    @Override
    public InsertMedalsType setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (InsertMedalsType) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public InsertMedalsType setQuotaUser(java.lang.String quotaUser) {
      return (InsertMedalsType) super.setQuotaUser(quotaUser);
    }

    @Override
    public InsertMedalsType setUserIp(java.lang.String userIp) {
      return (InsertMedalsType) super.setUserIp(userIp);
    }

    @Override
    public InsertMedalsType set(String parameterName, Object value) {
      return (InsertMedalsType) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMedalsType".
   *
   * This request holds the parameters needed by the the medals server.  After setting any optional
   * parameters, call the {@link ListMedalsType#execute()} method to invoke the remote operation.
   *
   * @return the request
   */
  public ListMedalsType listMedalsType() throws java.io.IOException {
    ListMedalsType result = new ListMedalsType();
    initialize(result);
    return result;
  }

  public class ListMedalsType extends MedalsRequest<com.google.api.services.medals.model.CollectionResponseMedalsType> {

    private static final String REST_PATH = "medalstype";

    /**
     * Create a request for the method "listMedalsType".
     *
     * This request holds the parameters needed by the the medals server.  After setting any optional
     * parameters, call the {@link ListMedalsType#execute()} method to invoke the remote operation.
     * <p> {@link ListMedalsType#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @since 1.13
     */
    protected ListMedalsType() {
      super(Medals.this, "GET", REST_PATH, null, com.google.api.services.medals.model.CollectionResponseMedalsType.class);
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMedalsType setAlt(java.lang.String alt) {
      return (ListMedalsType) super.setAlt(alt);
    }

    @Override
    public ListMedalsType setFields(java.lang.String fields) {
      return (ListMedalsType) super.setFields(fields);
    }

    @Override
    public ListMedalsType setKey(java.lang.String key) {
      return (ListMedalsType) super.setKey(key);
    }

    @Override
    public ListMedalsType setOauthToken(java.lang.String oauthToken) {
      return (ListMedalsType) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMedalsType setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMedalsType) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMedalsType setQuotaUser(java.lang.String quotaUser) {
      return (ListMedalsType) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMedalsType setUserIp(java.lang.String userIp) {
      return (ListMedalsType) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.String cursor;

    /**

     */
    public java.lang.String getCursor() {
      return cursor;
    }

    public ListMedalsType setCursor(java.lang.String cursor) {
      this.cursor = cursor;
      return this;
    }

    @com.google.api.client.util.Key
    private java.lang.Integer limit;

    /**

     */
    public java.lang.Integer getLimit() {
      return limit;
    }

    public ListMedalsType setLimit(java.lang.Integer limit) {
      this.limit = limit;
      return this;
    }

    @Override
    public ListMedalsType set(String parameterName, Object value) {
      return (ListMedalsType) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "listMedalsUser".
   *
   * This request holds the parameters needed by the the medals server.  After setting any optional
   * parameters, call the {@link ListMedalsUser#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public ListMedalsUser listMedalsUser(java.lang.Long id) throws java.io.IOException {
    ListMedalsUser result = new ListMedalsUser(id);
    initialize(result);
    return result;
  }

  public class ListMedalsUser extends MedalsRequest<com.google.api.services.medals.model.CollectionResponseMedals> {

    private static final String REST_PATH = "collectionresponse_medals/{id}";

    /**
     * Create a request for the method "listMedalsUser".
     *
     * This request holds the parameters needed by the the medals server.  After setting any optional
     * parameters, call the {@link ListMedalsUser#execute()} method to invoke the remote operation.
     * <p> {@link ListMedalsUser#initialize(com.google.api.client.googleapis.services.AbstractGoogleCl
     * ientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected ListMedalsUser(java.lang.Long id) {
      super(Medals.this, "GET", REST_PATH, null, com.google.api.services.medals.model.CollectionResponseMedals.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public ListMedalsUser setAlt(java.lang.String alt) {
      return (ListMedalsUser) super.setAlt(alt);
    }

    @Override
    public ListMedalsUser setFields(java.lang.String fields) {
      return (ListMedalsUser) super.setFields(fields);
    }

    @Override
    public ListMedalsUser setKey(java.lang.String key) {
      return (ListMedalsUser) super.setKey(key);
    }

    @Override
    public ListMedalsUser setOauthToken(java.lang.String oauthToken) {
      return (ListMedalsUser) super.setOauthToken(oauthToken);
    }

    @Override
    public ListMedalsUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (ListMedalsUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public ListMedalsUser setQuotaUser(java.lang.String quotaUser) {
      return (ListMedalsUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public ListMedalsUser setUserIp(java.lang.String userIp) {
      return (ListMedalsUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public ListMedalsUser setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public ListMedalsUser set(String parameterName, Object value) {
      return (ListMedalsUser) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateMedalsUser".
   *
   * This request holds the parameters needed by the the medals server.  After setting any optional
   * parameters, call the {@link UpdateMedalsUser#execute()} method to invoke the remote operation.
   *
   * @param id
   * @param content the {@link com.google.api.services.medals.model.CollectionResponseMedalsWin}
   * @return the request
   */
  public UpdateMedalsUser updateMedalsUser(java.lang.Long id, com.google.api.services.medals.model.CollectionResponseMedalsWin content) throws java.io.IOException {
    UpdateMedalsUser result = new UpdateMedalsUser(id, content);
    initialize(result);
    return result;
  }

  public class UpdateMedalsUser extends MedalsRequest<com.google.api.services.medals.model.CollectionResponseMedalsWin> {

    private static final String REST_PATH = "collectionresponse_medalswin/{id}";

    /**
     * Create a request for the method "updateMedalsUser".
     *
     * This request holds the parameters needed by the the medals server.  After setting any optional
     * parameters, call the {@link UpdateMedalsUser#execute()} method to invoke the remote operation.
     * <p> {@link UpdateMedalsUser#initialize(com.google.api.client.googleapis.services.AbstractGoogle
     * ClientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param id
     * @param content the {@link com.google.api.services.medals.model.CollectionResponseMedalsWin}
     * @since 1.13
     */
    protected UpdateMedalsUser(java.lang.Long id, com.google.api.services.medals.model.CollectionResponseMedalsWin content) {
      super(Medals.this, "PUT", REST_PATH, content, com.google.api.services.medals.model.CollectionResponseMedalsWin.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public UpdateMedalsUser setAlt(java.lang.String alt) {
      return (UpdateMedalsUser) super.setAlt(alt);
    }

    @Override
    public UpdateMedalsUser setFields(java.lang.String fields) {
      return (UpdateMedalsUser) super.setFields(fields);
    }

    @Override
    public UpdateMedalsUser setKey(java.lang.String key) {
      return (UpdateMedalsUser) super.setKey(key);
    }

    @Override
    public UpdateMedalsUser setOauthToken(java.lang.String oauthToken) {
      return (UpdateMedalsUser) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateMedalsUser setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateMedalsUser) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateMedalsUser setQuotaUser(java.lang.String quotaUser) {
      return (UpdateMedalsUser) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateMedalsUser setUserIp(java.lang.String userIp) {
      return (UpdateMedalsUser) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public UpdateMedalsUser setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public UpdateMedalsUser set(String parameterName, Object value) {
      return (UpdateMedalsUser) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Medals}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Medals}. */
    @Override
    public Medals build() {
      return new Medals(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link MedalsRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setMedalsRequestInitializer(
        MedalsRequestInitializer medalsRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(medalsRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
