/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-07 19:00:49 UTC)
 * on 2013-08-09 at 00:29:31 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.status.model;

/**
 * Model definition for Status.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Status extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long gameDraw;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long gameLost;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long gameWin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long id;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String statusGameDraw;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String statusGameLost;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String statusGameWin;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long total;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGameDraw() {
    return gameDraw;
  }

  /**
   * @param gameDraw gameDraw or {@code null} for none
   */
  public Status setGameDraw(java.lang.Long gameDraw) {
    this.gameDraw = gameDraw;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGameLost() {
    return gameLost;
  }

  /**
   * @param gameLost gameLost or {@code null} for none
   */
  public Status setGameLost(java.lang.Long gameLost) {
    this.gameLost = gameLost;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getGameWin() {
    return gameWin;
  }

  /**
   * @param gameWin gameWin or {@code null} for none
   */
  public Status setGameWin(java.lang.Long gameWin) {
    this.gameWin = gameWin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getId() {
    return id;
  }

  /**
   * @param id id or {@code null} for none
   */
  public Status setId(java.lang.Long id) {
    this.id = id;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatusGameDraw() {
    return statusGameDraw;
  }

  /**
   * @param statusGameDraw statusGameDraw or {@code null} for none
   */
  public Status setStatusGameDraw(java.lang.String statusGameDraw) {
    this.statusGameDraw = statusGameDraw;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatusGameLost() {
    return statusGameLost;
  }

  /**
   * @param statusGameLost statusGameLost or {@code null} for none
   */
  public Status setStatusGameLost(java.lang.String statusGameLost) {
    this.statusGameLost = statusGameLost;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getStatusGameWin() {
    return statusGameWin;
  }

  /**
   * @param statusGameWin statusGameWin or {@code null} for none
   */
  public Status setStatusGameWin(java.lang.String statusGameWin) {
    this.statusGameWin = statusGameWin;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTotal() {
    return total;
  }

  /**
   * @param total total or {@code null} for none
   */
  public Status setTotal(java.lang.Long total) {
    this.total = total;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public Status setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public Status set(String fieldName, Object value) {
    return (Status) super.set(fieldName, value);
  }

  @Override
  public Status clone() {
    return (Status) super.clone();
  }

}
