/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-07 19:00:49 UTC)
 * on 2013-08-09 at 00:29:38 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.medals.model;

/**
 * Model definition for MedalsWin.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class MedalsWin extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.Integer amout;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String nameMedal;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Integer getAmout() {
    return amout;
  }

  /**
   * @param amout amout or {@code null} for none
   */
  public MedalsWin setAmout(java.lang.Integer amout) {
    this.amout = amout;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getNameMedal() {
    return nameMedal;
  }

  /**
   * @param nameMedal nameMedal or {@code null} for none
   */
  public MedalsWin setNameMedal(java.lang.String nameMedal) {
    this.nameMedal = nameMedal;
    return this;
  }

  @Override
  public MedalsWin set(String fieldName, Object value) {
    return (MedalsWin) super.set(fieldName, value);
  }

  @Override
  public MedalsWin clone() {
    return (MedalsWin) super.clone();
  }

}
