/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-07 19:00:49 UTC)
 * on 2013-08-09 at 00:29:38 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.medals.model;

/**
 * Model definition for Medals.
 *
 * <p> This is the Java data model class that specifies how to parse/serialize into the JSON that is
 * transmitted over HTTP when working with the . For a detailed explanation see:
 * <a href="http://code.google.com/p/google-http-java-client/wiki/JSON">http://code.google.com/p/google-http-java-client/wiki/JSON</a>
 * </p>
 *
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public final class Medals extends com.google.api.client.json.GenericJson {

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long idMedals;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key
  private java.lang.String medalsType;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long total;

  /**
   * The value may be {@code null}.
   */
  @com.google.api.client.util.Key @com.google.api.client.json.JsonString
  private java.lang.Long userId;

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getIdMedals() {
    return idMedals;
  }

  /**
   * @param idMedals idMedals or {@code null} for none
   */
  public Medals setIdMedals(java.lang.Long idMedals) {
    this.idMedals = idMedals;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.String getMedalsType() {
    return medalsType;
  }

  /**
   * @param medalsType medalsType or {@code null} for none
   */
  public Medals setMedalsType(java.lang.String medalsType) {
    this.medalsType = medalsType;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getTotal() {
    return total;
  }

  /**
   * @param total total or {@code null} for none
   */
  public Medals setTotal(java.lang.Long total) {
    this.total = total;
    return this;
  }

  /**
   * @return value or {@code null} for none
   */
  public java.lang.Long getUserId() {
    return userId;
  }

  /**
   * @param userId userId or {@code null} for none
   */
  public Medals setUserId(java.lang.Long userId) {
    this.userId = userId;
    return this;
  }

  @Override
  public Medals set(String fieldName, Object value) {
    return (Medals) super.set(fieldName, value);
  }

  @Override
  public Medals clone() {
    return (Medals) super.clone();
  }

}
