/*
 * Licensed under the Apache License, Version 2.0 (the "License"); you may not use this file except
 * in compliance with the License. You may obtain a copy of the License at
 *
 * http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software distributed under the License
 * is distributed on an "AS IS" BASIS, WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express
 * or implied. See the License for the specific language governing permissions and limitations under
 * the License.
 */
/*
 * This code was generated by https://code.google.com/p/google-apis-client-generator/
 * (build: 2013-08-07 19:00:49 UTC)
 * on 2013-08-09 at 00:29:31 UTC 
 * Modify at your own risk.
 */

package com.google.api.services.status;

/**
 * Service definition for Status (v1).
 *
 * <p>
 * This is an API
 * </p>
 *
 * <p>
 * For more information about this service, see the
 * <a href="" target="_blank">API Documentation</a>
 * </p>
 *
 * <p>
 * This service uses {@link StatusRequestInitializer} to initialize global parameters via its
 * {@link Builder}.
 * </p>
 *
 * @since 1.3
 * @author Google, Inc.
 */
@SuppressWarnings("javadoc")
public class Status extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient {

  // Note: Leave this static initializer at the top of the file.
  static {
    com.google.api.client.util.Preconditions.checkState(
        com.google.api.client.googleapis.GoogleUtils.MAJOR_VERSION == 1 &&
        com.google.api.client.googleapis.GoogleUtils.MINOR_VERSION >= 15,
        "You are currently running with version %s of google-api-client. " +
        "You need at least version 1.15 of google-api-client to run version " +
        "1.15.0-rc of the  library.", com.google.api.client.googleapis.GoogleUtils.VERSION);
  }

  /**
   * The default encoded root URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_ROOT_URL = "https://testapi-16.appspot.com/_ah/api/";

  /**
   * The default encoded service path of the service. This is determined when the library is
   * generated and normally should not be changed.
   *
   * @since 1.7
   */
  public static final String DEFAULT_SERVICE_PATH = "status/v1/";

  /**
   * The default encoded base URL of the service. This is determined when the library is generated
   * and normally should not be changed.
   */
  public static final String DEFAULT_BASE_URL = DEFAULT_ROOT_URL + DEFAULT_SERVICE_PATH;

  /**
   * Constructor.
   *
   * <p>
   * Use {@link Builder} if you need to specify any of the optional parameters.
   * </p>
   *
   * @param transport HTTP transport, which should normally be:
   *        <ul>
   *        <li>Google App Engine:
   *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
   *        <li>Android: {@code newCompatibleTransport} from
   *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
   *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
   *        </li>
   *        </ul>
   * @param jsonFactory JSON factory, which may be:
   *        <ul>
   *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
   *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
   *        <li>Android Honeycomb or higher:
   *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
   *        </ul>
   * @param httpRequestInitializer HTTP request initializer or {@code null} for none
   * @since 1.7
   */
  public Status(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
      com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
    this(new Builder(transport, jsonFactory, httpRequestInitializer));
  }

  /**
   * @param builder builder
   */
  Status(Builder builder) {
    super(builder);
  }

  @Override
  protected void initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest<?> httpClientRequest) throws java.io.IOException {
    super.initialize(httpClientRequest);
  }

  /**
   * Create a request for the method "addStatus".
   *
   * This request holds the parameters needed by the the status server.  After setting any optional
   * parameters, call the {@link AddStatus#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.google.api.services.status.model.GeneratedStatus}
   * @return the request
   */
  public AddStatus addStatus(com.google.api.services.status.model.GeneratedStatus content) throws java.io.IOException {
    AddStatus result = new AddStatus(content);
    initialize(result);
    return result;
  }

  public class AddStatus extends StatusRequest<com.google.api.services.status.model.Status> {

    private static final String REST_PATH = "addStatus";

    /**
     * Create a request for the method "addStatus".
     *
     * This request holds the parameters needed by the the status server.  After setting any optional
     * parameters, call the {@link AddStatus#execute()} method to invoke the remote operation. <p>
     * {@link
     * AddStatus#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.status.model.GeneratedStatus}
     * @since 1.13
     */
    protected AddStatus(com.google.api.services.status.model.GeneratedStatus content) {
      super(Status.this, "POST", REST_PATH, content, com.google.api.services.status.model.Status.class);
    }

    @Override
    public AddStatus setAlt(java.lang.String alt) {
      return (AddStatus) super.setAlt(alt);
    }

    @Override
    public AddStatus setFields(java.lang.String fields) {
      return (AddStatus) super.setFields(fields);
    }

    @Override
    public AddStatus setKey(java.lang.String key) {
      return (AddStatus) super.setKey(key);
    }

    @Override
    public AddStatus setOauthToken(java.lang.String oauthToken) {
      return (AddStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public AddStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (AddStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public AddStatus setQuotaUser(java.lang.String quotaUser) {
      return (AddStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public AddStatus setUserIp(java.lang.String userIp) {
      return (AddStatus) super.setUserIp(userIp);
    }

    @Override
    public AddStatus set(String parameterName, Object value) {
      return (AddStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "getSingleStatus".
   *
   * This request holds the parameters needed by the the status server.  After setting any optional
   * parameters, call the {@link GetSingleStatus#execute()} method to invoke the remote operation.
   *
   * @param id
   * @return the request
   */
  public GetSingleStatus getSingleStatus(java.lang.Long id) throws java.io.IOException {
    GetSingleStatus result = new GetSingleStatus(id);
    initialize(result);
    return result;
  }

  public class GetSingleStatus extends StatusRequest<com.google.api.services.status.model.Status> {

    private static final String REST_PATH = "status/{id}";

    /**
     * Create a request for the method "getSingleStatus".
     *
     * This request holds the parameters needed by the the status server.  After setting any optional
     * parameters, call the {@link GetSingleStatus#execute()} method to invoke the remote operation.
     * <p> {@link GetSingleStatus#initialize(com.google.api.client.googleapis.services.AbstractGoogleC
     * lientRequest)} must be called to initialize this instance immediately after invoking the
     * constructor. </p>
     *
     * @param id
     * @since 1.13
     */
    protected GetSingleStatus(java.lang.Long id) {
      super(Status.this, "GET", REST_PATH, null, com.google.api.services.status.model.Status.class);
      this.id = com.google.api.client.util.Preconditions.checkNotNull(id, "Required parameter id must be specified.");
    }

    @Override
    public com.google.api.client.http.HttpResponse executeUsingHead() throws java.io.IOException {
      return super.executeUsingHead();
    }

    @Override
    public com.google.api.client.http.HttpRequest buildHttpRequestUsingHead() throws java.io.IOException {
      return super.buildHttpRequestUsingHead();
    }

    @Override
    public GetSingleStatus setAlt(java.lang.String alt) {
      return (GetSingleStatus) super.setAlt(alt);
    }

    @Override
    public GetSingleStatus setFields(java.lang.String fields) {
      return (GetSingleStatus) super.setFields(fields);
    }

    @Override
    public GetSingleStatus setKey(java.lang.String key) {
      return (GetSingleStatus) super.setKey(key);
    }

    @Override
    public GetSingleStatus setOauthToken(java.lang.String oauthToken) {
      return (GetSingleStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public GetSingleStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (GetSingleStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public GetSingleStatus setQuotaUser(java.lang.String quotaUser) {
      return (GetSingleStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public GetSingleStatus setUserIp(java.lang.String userIp) {
      return (GetSingleStatus) super.setUserIp(userIp);
    }

    @com.google.api.client.util.Key
    private java.lang.Long id;

    /**

     */
    public java.lang.Long getId() {
      return id;
    }

    public GetSingleStatus setId(java.lang.Long id) {
      this.id = id;
      return this;
    }

    @Override
    public GetSingleStatus set(String parameterName, Object value) {
      return (GetSingleStatus) super.set(parameterName, value);
    }
  }

  /**
   * Create a request for the method "updateStatus".
   *
   * This request holds the parameters needed by the the status server.  After setting any optional
   * parameters, call the {@link UpdateStatus#execute()} method to invoke the remote operation.
   *
   * @param content the {@link com.google.api.services.status.model.GeneratedStatus}
   * @return the request
   */
  public UpdateStatus updateStatus(com.google.api.services.status.model.GeneratedStatus content) throws java.io.IOException {
    UpdateStatus result = new UpdateStatus(content);
    initialize(result);
    return result;
  }

  public class UpdateStatus extends StatusRequest<com.google.api.services.status.model.Status> {

    private static final String REST_PATH = "status";

    /**
     * Create a request for the method "updateStatus".
     *
     * This request holds the parameters needed by the the status server.  After setting any optional
     * parameters, call the {@link UpdateStatus#execute()} method to invoke the remote operation. <p>
     * {@link
     * UpdateStatus#initialize(com.google.api.client.googleapis.services.AbstractGoogleClientRequest)}
     * must be called to initialize this instance immediately after invoking the constructor. </p>
     *
     * @param content the {@link com.google.api.services.status.model.GeneratedStatus}
     * @since 1.13
     */
    protected UpdateStatus(com.google.api.services.status.model.GeneratedStatus content) {
      super(Status.this, "POST", REST_PATH, content, com.google.api.services.status.model.Status.class);
    }

    @Override
    public UpdateStatus setAlt(java.lang.String alt) {
      return (UpdateStatus) super.setAlt(alt);
    }

    @Override
    public UpdateStatus setFields(java.lang.String fields) {
      return (UpdateStatus) super.setFields(fields);
    }

    @Override
    public UpdateStatus setKey(java.lang.String key) {
      return (UpdateStatus) super.setKey(key);
    }

    @Override
    public UpdateStatus setOauthToken(java.lang.String oauthToken) {
      return (UpdateStatus) super.setOauthToken(oauthToken);
    }

    @Override
    public UpdateStatus setPrettyPrint(java.lang.Boolean prettyPrint) {
      return (UpdateStatus) super.setPrettyPrint(prettyPrint);
    }

    @Override
    public UpdateStatus setQuotaUser(java.lang.String quotaUser) {
      return (UpdateStatus) super.setQuotaUser(quotaUser);
    }

    @Override
    public UpdateStatus setUserIp(java.lang.String userIp) {
      return (UpdateStatus) super.setUserIp(userIp);
    }

    @Override
    public UpdateStatus set(String parameterName, Object value) {
      return (UpdateStatus) super.set(parameterName, value);
    }
  }

  /**
   * Builder for {@link Status}.
   *
   * <p>
   * Implementation is not thread-safe.
   * </p>
   *
   * @since 1.3.0
   */
  public static final class Builder extends com.google.api.client.googleapis.services.json.AbstractGoogleJsonClient.Builder {

    /**
     * Returns an instance of a new builder.
     *
     * @param transport HTTP transport, which should normally be:
     *        <ul>
     *        <li>Google App Engine:
     *        {@code com.google.api.client.extensions.appengine.http.UrlFetchTransport}</li>
     *        <li>Android: {@code newCompatibleTransport} from
     *        {@code com.google.api.client.extensions.android.http.AndroidHttp}</li>
     *        <li>Java: {@link com.google.api.client.googleapis.javanet.GoogleNetHttpTransport#newTrustedTransport()}
     *        </li>
     *        </ul>
     * @param jsonFactory JSON factory, which may be:
     *        <ul>
     *        <li>Jackson: {@code com.google.api.client.json.jackson2.JacksonFactory}</li>
     *        <li>Google GSON: {@code com.google.api.client.json.gson.GsonFactory}</li>
     *        <li>Android Honeycomb or higher:
     *        {@code com.google.api.client.extensions.android.json.AndroidJsonFactory}</li>
     *        </ul>
     * @param httpRequestInitializer HTTP request initializer or {@code null} for none
     * @since 1.7
     */
    public Builder(com.google.api.client.http.HttpTransport transport, com.google.api.client.json.JsonFactory jsonFactory,
        com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      super(
          transport,
          jsonFactory,
          DEFAULT_ROOT_URL,
          DEFAULT_SERVICE_PATH,
          httpRequestInitializer,
          false);
    }

    /** Builds a new instance of {@link Status}. */
    @Override
    public Status build() {
      return new Status(this);
    }

    @Override
    public Builder setRootUrl(String rootUrl) {
      return (Builder) super.setRootUrl(rootUrl);
    }

    @Override
    public Builder setServicePath(String servicePath) {
      return (Builder) super.setServicePath(servicePath);
    }

    @Override
    public Builder setHttpRequestInitializer(com.google.api.client.http.HttpRequestInitializer httpRequestInitializer) {
      return (Builder) super.setHttpRequestInitializer(httpRequestInitializer);
    }

    @Override
    public Builder setApplicationName(String applicationName) {
      return (Builder) super.setApplicationName(applicationName);
    }

    @Override
    public Builder setSuppressPatternChecks(boolean suppressPatternChecks) {
      return (Builder) super.setSuppressPatternChecks(suppressPatternChecks);
    }

    @Override
    public Builder setSuppressRequiredParameterChecks(boolean suppressRequiredParameterChecks) {
      return (Builder) super.setSuppressRequiredParameterChecks(suppressRequiredParameterChecks);
    }

    @Override
    public Builder setSuppressAllChecks(boolean suppressAllChecks) {
      return (Builder) super.setSuppressAllChecks(suppressAllChecks);
    }

    /**
     * Set the {@link StatusRequestInitializer}.
     *
     * @since 1.12
     */
    public Builder setStatusRequestInitializer(
        StatusRequestInitializer statusRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(statusRequestInitializer);
    }

    @Override
    public Builder setGoogleClientRequestInitializer(
        com.google.api.client.googleapis.services.GoogleClientRequestInitializer googleClientRequestInitializer) {
      return (Builder) super.setGoogleClientRequestInitializer(googleClientRequestInitializer);
    }
  }
}
